import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/theme/provider";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/context/convex-auth-provider";
import SyncUser from "@/components/SyncUser";
import ReduxProvider from "@/redux/provider";
import { ProfileQuery } from "@/convex/query.config";
import { ConvexUserRaw, normalizeProfile } from "@/types/users";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const redaction10Font = localFont({
  src: [
    {
      path: "./fonts/Redaction/Redaction10Italic.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-redaction-ten",
  display: "swap",
});
const redaction50Font = localFont({
  src: [
    {
      path: "./fonts/Redaction/Redaction50Italic.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-redaction-fifty",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ulaseb  - Sketch to Design Aluminium",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const rawProfile = await ProfileQuery();
  // const profile = normalizeProfile(
  //   rawProfile as unknown as ConvexUserRaw | null
  // );

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${redaction10Font.variable} ${redaction50Font.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ConvexClientProvider>
              {/* <ReduxProvider preloadState={{ profile }}> */}
              <main className="relative w-full max-w-full h-screen">
                {children}
              </main>
              {/* </ReduxProvider> */}
              <SyncUser />
            </ConvexClientProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
